//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CoreMonitorIcon {
            get {
                object obj = ResourceManager.GetObject("CoreMonitorIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;CoreMonitor
        ///        &lt;!--CoreMonitorVersion--&gt;
        ///    &lt;/title&gt;
        ///    &lt;link href=&quot;./Style.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;header&quot;&gt;  
        ///        &lt;div id=&quot;headertext&quot;&gt;
        ///            &lt;h3&gt;
        ///                v&lt;!--CoreMonitorVersion--&gt;&lt;/h3&gt;
        ///            &lt;a href=&quot;http://localhost:56302&quot;&gt;&lt;h1&gt;
        ///                CoreMonitor&lt;/h1&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;body&quot;&gt;
        ///        &lt;h2&gt;HTTP API Documentation&lt;/h2&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///        &lt;link rel=&quot;Stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot; /&gt;
        ///		&lt;title&gt;CoreMonitor - Notifications&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///   &lt;div id=&quot;header&quot;&gt;  
        ///        &lt;div id=&quot;headertext&quot;&gt;
        ///            &lt;h3&gt;
        ///                v&lt;!--CoreMonitorVersion--&gt;&lt;/h3&gt;
        ///            &lt;a href=&quot;http://localhost:56302&quot;&gt;&lt;h1&gt;
        ///                CoreMonitor&lt;/h1&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;body&quot;&gt;
        ///        &lt;h2&gt;Notifications API&lt;/h2&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///        &lt;link rel=&quot;Stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot; /&gt;
        ///		&lt;title&gt;CoreMonitor - Notifications&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///   &lt;div id=&quot;header&quot;&gt;  
        ///        &lt;div id=&quot;headertext&quot;&gt;
        ///            &lt;h3&gt;
        ///                v&lt;!--CoreMonitorVersion--&gt;&lt;/h3&gt;
        ///            &lt;a href=&quot;http://localhost:56302&quot;&gt;&lt;h1&gt;
        ///                CoreMonitor&lt;/h1&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;body&quot;&gt;
        ///        &lt;h2&gt;Notifications API&lt;/h2&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///    font-family: Arial;
        ///    margin: 0px;
        ///    font-size:10pt;
        ///    background: #eee;
        ///}
        ///
        ///h1 
        ///{
        ///    font-size: 20pt;
        ///    padding: 10px;
        ///    margin: 0px;
        ///}
        ///
        ///h2 
        ///{
        ///    font-size: 16pt;
        ///    padding: 5px;
        ///    margin: 0px;
        ///}
        ///
        ///h3 
        ///{
        ///    font-size: 12pt;
        ///    font-weight: bold;
        ///    padding: 2px;
        ///    margin: 0px;
        ///}
        ///
        ///#header 
        ///{
        ///    background: #fff;    
        ///    background: -webkit-linear-gradient(#fff, #eee);
        ///    background: -moz-linear-gradient(#fff, #eee);
        ///    background: -o-linear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Success {
            get {
                object obj = ResourceManager.GetObject("Success", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
